# Generated by Django 4.1 on 2022-08-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
