# Generated by Django 4.1 on 2022-08-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_photo_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_subtext',
        ),
        migrations.AddField(
            model_name='photo',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
