# Generated by Django 4.1 on 2022-08-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_photo_photo_subtext_photo_subtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
